Updated quick installation
AOT-Technologies/forms-flow-ai-deployment pull request #30
Opened 2022-12-27 13:31 UTC by alanraju-aot

1. Fixed versions for data bases
2. reduced script size
3. added IP confirmation to avoid IP issues

2022-12-27 13:50 UTC, sreehari-aot requested changes

2022-12-27 13:50 UTC, sreehari-aot commented on scripts/install.bash
>          docker-compose -f docker-compose.yml up -d
can use `docker-compose up -d`

2022-12-27 13:50 UTC, sreehari-aot commented on scripts/install.bash
>          docker-compose -f docker-compose.yml up -d
since we are using `docker-compose.yml` as file name we can remove the `-f` flag everywhere

2022-12-27 13:50 UTC, sreehari-aot commented on scripts/install.bat
> +    set /p ip-addr=Confirm that your IPv4 address is %ip-add%? [y/n]
Use proper naming conventions for variables to avoid confusion. Here I think you are the first victim of bad naming, 
line 48 the variable should be `ip-add` if you are intend to override the IP collected by the script with the user input. For line 44 better variable name should be `choice` which is used by the bash counterpart.

So the suggested changes would be replace `ip-aadr` with `choice` except line 48 where `ip-addr` should be replaced with `ip-add`

2022-12-27 13:50 UTC, sreehari-aot commented on scripts/uninstall.bat
>      docker volume prune -f
For uninstall, we should be more specific about what are we about to remove. It's a bad practice to remove the things that we are not intending to remove, here using the `docker`  command would affect other images and caches present in the user system. A better alternative is to specify the exact image that we are removing. eg: `docker image rm <image_id>`

2022-12-27 14:12 UTC, alanraju-aot commented on scripts/uninstall.bat
>      docker volume prune -f
Docker images were not able to clear using command line, the users have to manually delete it from the docker, only volumes and system caches can be removed using commands.

2022-12-27 14:16 UTC, sreehari-aot requested changes

2022-12-27 14:16 UTC, sreehari-aot commented on scripts/install.bash
> -    docker-compose -f analytics-docker-compose.yml up --build -d
here you need `-f`. only for the default file name, we can avoid the flag which is `docker-compose. yml`

2022-12-28 07:49 UTC, sreehari-aot approved these changes
LGTM!

2022-12-28 07:52 UTC, abilpraju-aot approved these changes

2022-12-28 08:29 UTC, merged