image updated
AOT-Technologies/forms-flow-ai-deployment pull request #51
Opened 2023-07-10 09:58 UTC by alanraju-aot

image updated to v5.2.0

2023-07-10 11:21 UTC, sumesh-aot approved these changes

2023-07-10 18:51 UTC, abhilash-aot commented on docker-compose/docker-compose-arm64.yml
> +      # - MF_FORMSFLOW_WEB_URL=${MF_FORMSFLOW_WEB_URL:-https://forms-flow-microfrontends.aot-technologies.com/forms-flow-web@v5.2.0/single-spa-build.gz.js}
The defaults value is changed from spa to formsflow -web copy latest sample.env from master of ffai repo

2023-07-11 02:19 UTC, shuhaib-aot approved these changes

2023-07-11 02:20 UTC, shuhaib-aot requested changes
Please change the web s3url

2023-07-11 04:14 UTC, shuhaib-aot approved these changes

2023-07-11 04:15 UTC, merged